version: '3'

services:
  nginx:
    image: nginx:1.25.3
    container_name: nginx
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
      - /home/docker/mount/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/docker/mount/nginx/conf/conf.d:/etc/nginx/conf.d
      - /home/docker/mount/nginx/html:/usr/share/nginx/html
      - /home/docker/mount/nginx/project:/home/nginx/project
      - /home/docker/mount/nginx/log:/var/log/nginx
